#!/bin/bash
#install git
sudo apt-get install git
#install cmake
sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ xenial main'
sudo apt-get update
sudo apt-get install cmake
#install libxerces-c-dev
sudo apt-get install libxerces-c-dev
#install qt
sudo apt-get install qt5-default
#install libxmu-dev
sudo apt-get install libxmu-dev

#for ROOT 6.20
sudo apt-get install libxpm-dev
sudo apt-get install libxft-dev
#install qtcreator
sudo apt install qtcreator
